version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  scraper:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/src
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: python -m src.api.server
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.cron
    depends_on:
      - api
      - postgres
    volumes:
      - ./logs:/var/log
    restart: unless-stopped

volumes:
  postgres_data: